### ISSUE TITLE
CODE_OF_CONDUCT references another organisation in enforcement

### ISSUE THREAD

**Issue by smithtj** [anthonyLuttrell/wwa#13]
Change the enforcement section of the CODE_OF_CONDUCT to reference the individuals/team that will be handling the community enforcement for this project. 

Currently, this section reads:

> Instances of abusive, harassing, or otherwise unacceptable behavior may be reported by contacting **the project team at jacks4l@cmich.edu**.

**Comment by RedRoyalDog** [comment]
Good catch! Do you want to update it to involve contacting an admin on discord? I'll accept a PR for this.

**Comment by smithtj** [comment]
Sure, shall I link the discord/list the admins, or just leave it as 'contacting an admin on the World War Ants discord'?

**Comment by RedRoyalDog** [comment]
Something along those lines sounds good. Make sure to link the Discord.

**Comment by smithtj** [comment]
Created a PR: #14

**Comment by RedRoyalDog** [comment]
Resolved in #14
