### ISSUE TITLE
Add a .gitignore

### ISSUE THREAD

**Issue by shamsquatch** [anthonyLuttrell/wwa#2]
It would be good to add a gitignore file. Should contain extensions and folders generated by IDEs. Compiled targets, e.g. .class files.

**Comment by anthonyLuttrell** [comment]
Ah ha! I was wondering about that. I will add.

**Comment by EhWhoAmI** [comment]
doing that

**Comment by mdave16** [comment]
@EhWhoAmI, May be worth closing Issues using commit messages or in pull requests themselves next time :P

https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by EhWhoAmI** [comment]
I cant close because no admin access. I wanted to.

**Comment by shamsquatch** [comment]
Closed in #3
